[package]
name = "cpulimit"
version = "0.1.0"
edition = "2021"

[dependencies]
cpulimiter = { path = "../cpulimiter", version = "0.1.0" }

[dependencies.clap]
version = "3.1.15"
features = ["derive", "color", "suggestions"]
